name: ci

on: [push, pull_request]

jobs:
  Type-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Module
        uses: actions/checkout@v2
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: 🧐 Type Check
        run: deno test --no-run ./dev/typecheck.ts
